server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3307}/ai_service
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rajni}

  ai:
    chat:
      client:
        enabled: true

    mcp:
      client:
        name: search-client

        streamable-http:
          connections:
            search-service:
              url: ${SEARCH_SERVICE_URL:http://localhost:9099}
              endpoint: /mcp

    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}

      chat:
        model: llama3.2:3b

      embedding:
        model: nomic-embed-text

      init:
        timeout: 5m

    retry:
      max-attempts: 1

    vectorstore:
      mariadb:
        initialize-schema: true
        distance-type: COSINE
        dimensions: 768

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ai-service-groups
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ecommerce.aiservice.kafka.ProductCreatedEventDTO
