server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**

        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profile/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: my-super-secret-key-my-super-secret-key
