server:
  port: 8080

spring:
  application:
    name: api-gatway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**

        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profile/**
        
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: my-super-secret-key-my-super-secret-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
