server:
  port: 9090

security:
  jwt:
    secret: my-super-secret-key-my-super-secret-key
    expiration: 86400000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce?useSSL=false&serverTimezone=UTC
    username: root
    password: rajni
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
