server:
  port: 9096

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_orderservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rajni
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 2147483647
      properties:
        acks: all
        enable-idempotence: true
        max-in-flight-requests-per-connection: 5
        spring.json.add.type.headers: true

    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.use.type.headers: true
        spring.json.trusted.packages: com.ecommerce.orderservice.events
        spring.json.type.mapping: >
          com.ecommerce.inventoryservice.event.InventoryReservedEvent:
          com.ecommerce.orderservice.events.InventoryReservedEvent,
          com.ecommerce.inventoryservice.event.InventoryFailedEvent:
          com.ecommerce.orderservice.events.InventoryFailedEvent,
          com.ecommerce.paymentservice.event.PaymentCompletedEvent:
          com.ecommerce.orderservice.events.PaymentCompletedEvent

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
