server:
  port: 9097
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_productservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rajni
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    admin:
      fail-fast: false
      auto-create: false
    properties:
      client:
        dns:
          lookup: use_all_dns_ips
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
