server:
  port: 9099

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true

spring:

  datasource:
    url: jdbc:mariadb://${DB_HOST:mariadb}:${DB_PORT:3307}/search_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rajni}

  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: search-service-groups
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ecommerce.searchservice.DTO.ProductCreatedEvent

  ai:
    mcp:
      server:
        enabled: true
        protocol: STREAMABLE
        
        name: ecommerce-search-mcp
        version: 1.0.0
        type: SYNC
        request-timeout: 30s

        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
          
        streamable-http:
          mcp-endpoint: /mcp
